CREATE OR REPLACE DYNAMIC TABLE YTL_{{environment}}.GOLD.CUSTOMER_GIFT
TARGET_LAG = '5 minutes'
WAREHOUSE = COMPUTE_XS
AS

SELECT  A.CUSTOMER_NAME,
        A.CUSTOMERTIER,
        B.GIFT
FROM YTL_{{environment}}.SILVER.CUSTOMER_TIERS A
JOIN YTL_{{environment}}.BRONZE.TIER_GIFT B
  ON A.CUSTOMERTIER = B.TIER;